---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
geoserver:
  version: 1.1.3-SNAPSHOT-d5525b3
portal:
  version: 1.1.3-SNAPSHOT-7e4eff3
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-4e3b915
apache:
  version: 1.1.3-SNAPSHOT-7e4eff3
solr:
  version: 1.1.3-SNAPSHOT-4e3b915
  storage:
    type: ssd
