---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
  database: powo
geoserver:
  version: 1.1.3-SNAPSHOT-51c4049
portal:
  version: 1.1.3-SNAPSHOT-51c4049
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-51c4049
apache:
  version: 1.1.3-SNAPSHOT-51c4049
solr:
  version: 1.1.3-SNAPSHOT-51c4049
  storage:
    type: ssd
