---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
geoserver:
  version: 1.1.3-SNAPSHOT-b65656a
portal:
  version: 1.1.3-SNAPSHOT-22f01d2
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-7efa65c
apache:
  version: 1.1.3-SNAPSHOT-22f01d2
solr:
  version: 1.1.3-SNAPSHOT-22f01d2
  storage:
    type: ssd
