---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
  database: powo
geoserver:
  version: 1.1.3-SNAPSHOT-35ab607
portal:
  version: 1.1.3-SNAPSHOT-70ec35d
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-70ec35d
apache:
  version: 1.1.3-SNAPSHOT-70ec35d
solr:
  version: 1.1.3-SNAPSHOT-35ab607
  storage:
    type: ssd
