---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
  database: powo_1
  user: emonocot
geoserver:
  version: 2.0.0-315c245
portal:
  version: 2.0.0-315c245
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
harvester:
  version: 2.0.0-315c245
apache:
  version: 2.0.0-315c245
solr:
  version: 2.0.0-315c245
  storage:
    type: ssd
