---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
geoserver:
  version: 1.1.3-SNAPSHOT-d5525b3
portal:
  version: 1.1.3-SNAPSHOT-9097725
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-e75a3a7
apache:
  version: 1.1.3-SNAPSHOT-9097725
solr:
  version: 1.1.3-SNAPSHOT-d5525b3
  storage:
    type: ssd
