---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
portal:
  version: 1.1.3-SNAPSHOT-79df5e5
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-79df5e5
apache:
  version: 1.1.3-SNAPSHOT-79df5e5
