---
db:
  cloudsql:
    enabled: true
    connection: powop-1349:europe-west1:powop-prod-db
portal:
  version: 1.1.3-SNAPSHOT-dc2f0e3
  replicas: 2
harvester:
  version: 1.1.3-SNAPSHOT-dc2f0e3
apache:
  version: 1.1.3-SNAPSHOT-dc2f0e3
