apiVersion: v1
kind: Secret
metadata:
  name: deployer-secrets
type: Opaque
data:
  service-account.json: {{ .Values.sa.deployer | b64enc | quote }}
  secrets.yaml: |-
    password:
      {{ .Values.password | toYaml | b64enc | quote }}
