apiVersion: v1
kind: Secret
metadata:
  name: deployer-secrets
type: Opaque
data:
  service-account.json: {{ .Values.sa.deployer | b64enc | quote }}
  secrets.yaml: {{ printf "passwords:\n  cdn: %s\n  db: %s\n  geoserver: %s\n" .Values.password.cdn .Values.password.db .Values.password.geoserver | b64enc | quote }}
