apiVersion: v1
kind: Secret
metadata:
  name: deployer-secrets
type: Opaque
data:
  service-account.json: {{ .Values.sa.deployer | b64enc | quote }}
  secrets.yaml: {{ printf "password:\n%s" (.Values.password | toYaml | indent 2) | b64enc | quote }}
