apiVersion: v1
kind: Secret
metadata:
  name: deployer-secrets
type: Opaque
data:
  service-account.json: {{ .Values.sa.deployer | b64enc | quote }}
  secrets.yaml: {{ printf "password:\n  cdn: %s\n  db: %s\n  geoserver: %s\n  harvester: %s\n" .Values.password.cdn .Values.password.db .Values.password.geoserver .Values.password.harvester | b64enc | quote }}
