apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: {{ .Values.apache.replicas }}
  template:
    metadata:
      labels:
        name: apache
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: apache
          env:
            - name: PORTAL
              value: portal
          image: eu.gcr.io/powop-1349/apache:{{ .Values.apache.version }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    name: apache
spec:
  selector:
    name: apache
  ports:
    - port: 80
  type: LoadBalancer
