{{- if .Values.colfungi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-colfungi
spec:
  replicas: {{ .Values.colfungi.portal.replicas }}
  template:
    metadata:
      labels:
        name: portal-colfungi
        env: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-db
          image: mariadb:10.3.5
          command: ['sh', '-c', 'until mysqladmin ping --host db; do echo waiting for db; sleep 2; done']
      containers:
        - name: portal-colfungi
          image: eu.gcr.io/powop-1349/portal:{{ .Values.portal.version }}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.portal.resources | indent 12 }}
          env:
            - name: SITE_VARIANT
              value: ColFungiSite
{{- if .Values.password.db }}
            - name: JDBC_DRIVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: jdbc-driver-password
{{- end }}
{{- if .Values.db.user }}
            - name: JDBC_DRIVER_USERNAME
              value: {{ .Values.db.user }}
{{- end }}
{{- if .Values.portal.google_analytics_code }}
            - name: GOOGLE_ANALYTICS_CODE
              value: {{ .Values.portal.google_analytics_code }}
{{- end }}
{{- if .Values.password.cdn }}
            - name: CDN_KEY
              valueFrom:
                secretKeyRef:
                  name: service-keys
                  key: cdn-key
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: portal-colfungi
  labels:
    name: portal-colfungi
spec:
  selector:
    name: portal-colfungi
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-colfungi
spec:
  replicas: {{ .Values.colfungi.ingress.replicas }}
  template:
    metadata:
      labels:
        name: ingress-colfungi
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: ingress-colfungi
          image: eu.gcr.io/powop-1349/ingress:{{ .Values.portal.version }}
          env:
            - name: PORTAL
              value: portal-colfungi
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
{{ toYaml .Values.ingress.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-colfungi
  labels:
    name: ingress-colfungi
spec:
  selector:
    name: ingress-colfungi
  ports:
    - port: 80
  type: LoadBalancer
{{- end }}
