apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geodb
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: geodb
          image: eu.gcr.io/powop-1349/geodb:{{ .Values.geoserver.version }}
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: geodb
  labels:
    name: geodb
spec:
  selector:
    name: geodb
  ports:
    - port: 3306
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geoserver
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: geoserver
          image: eu.gcr.io/powop-1349/geoserver:{{ .Values.geoserver.version }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.geoserver.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    name: geoserver
spec:
  selector:
    name: geoserver
  ports:
    - port: 8080
