apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harvester
spec:
  replicas: {{ .Values.harvester.replicas }}
  template:
    metadata:
      labels:
        name: harvester
        env: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-db
          image: mariadb:10.3.5
          command: ['sh', '-c', 'until mysqladmin ping --host db; do echo waiting for db; sleep 2; done']
      containers:
        - name: harvester
          image: eu.gcr.io/powop-1349/harvester:{{ .Values.harvester.version }}
          ports:
            - containerPort: 8009
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /harvester/ping
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
          env:
{{- if .Values.db.password }}
            - name: JDBC_DRIVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: jdbc-driver-password
{{- end }}
{{- if .Values.db.user }}
            - name: JDBC_DRIVER_USERNAME
              value: {{ .Values.db.user }}
{{- end }}
{{- if .Values.cdn_key }}
            - name: CDN_KEY
              valueFrom:
                secretKeyRef:
                  name: service-keys
                  key: cdn-key
{{- end }}
{{- if .Values.db.cloudsql.enabled }}
            - name: JDBC_DRIVER_URL
              value: jdbc:mysql://127.0.0.1:3306/{{ .Values.db.database }}
{{- template "cloudsql_proxy" . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: harvester
spec:
  selector:
    name: harvester
  ports:
    - port: 8009
