apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  replicas: {{ .Values.ingress.replicas }}
  selector:
    matchLabels:
      name: ingress
      env: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: ingress
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: ingress
          env:
            - name: PORTAL
              value: portal
          image: eu.gcr.io/powop-1349/ingress:{{ .Values.portal.version }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
{{ toYaml .Values.ingress.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  labels:
    name: ingress
spec:
  selector:
    name: ingress
  ports:
    - port: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
