apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  jdbc-driver-password: {{ .Values.db.password | b64enc | quote }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-database: {{ .Values.db.database | b64enc | quote }}
  mysql-user: {{ .Values.db.user | b64enc | quote }}
  mysql-password: {{ .Values.db.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: geo-db-secrets
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-database: {{ .Values.geoserver.database | b64enc | quote }}
  mysql-user: {{ .Values.geoserver.user | b64enc | quote }}
  mysql-password: {{ .Values.geoserver.password | b64enc | quote }}
{{- if .Values.db.cloudsql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-oauth-credentials
type: Opaque
data:
  cloudsql-credentials.json: {{ .Values.db.cloudsql.credentials | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: service-keys
type: Opaque
data:
{{- if .Values.google_analytics_code }}
  google-analytics-code: {{ .Values.google_analytics_code | b64enc | quote }}
{{- end }}
{{- if .Values.cdn_key }}
  cdn-key: {{ .Values.cdn_key | b64enc | quote }}
{{- end }}
---
