{{- if .Values.upb.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal-upb
spec:
  replicas: {{ .Values.upb.portal.replicas }}
  template:
    metadata:
      labels:
        name: portal-upb
        env: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-db
          image: mariadb:10.3.5
          command: ['sh', '-c', 'until mysqladmin ping --host db; do echo waiting for db; sleep 2; done']
      containers:
        - name: portal-upb
          image: eu.gcr.io/powop-1349/portal:{{ .Values.portal.version }}
          ports:
            - containerPort: 8009
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
          env:
            - name: SITE_VARIANT
              value: UPBSite
{{- if .Values.password.db }}
            - name: JDBC_DRIVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: jdbc-driver-password
{{- end }}
{{- if .Values.db.user }}
            - name: JDBC_DRIVER_USERNAME
              value: {{ .Values.db.user }}
{{- end }}
{{- if .Values.portal.google_analytics_code }}
            - name: GOOGLE_ANALYTICS_CODE
              value: {{ .Values.portal.google_analytics_code }}
{{- end }}
{{- if .Values.password.cdn }}
            - name: CDN_KEY
              valueFrom:
                secretKeyRef:
                  name: service-keys
                  key: cdn-key
{{- end }}
{{- if .Values.db.cloudsql.enabled }}
            - name: JDBC_DRIVER_URL
              value: jdbc:mysql://127.0.0.1:3306/{{ .Values.db.database }}
{{- template "cloudsql_proxy" . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: portal-upb
  labels:
    name: portal-upb
spec:
  selector:
    name: portal-upb
  ports:
    - port: 8009
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-upb
spec:
  replicas: {{ .Values.upb.apache.replicas }}
  template:
    metadata:
      labels:
        name: apache-upb
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: apache-upb
          image: eu.gcr.io/powop-1349/apache:{{ .Values.portal.version }}
          env:
            - name: PORTAL
              value: portal-upb
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: apache-upb
  labels:
    name: apache-upb
spec:
  selector:
    name: apache-upb
  ports:
    - port: 80
  type: LoadBalancer
{{- end }}
