apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: activemq
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:5.12.0
          ports:
            - containerPort: 61616
