apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: apache
    spec:
      containers:
        - name: apache
          image: eu.gcr.io/powop-1349/apache:latest
          ports:
            - containerPort: 80
