apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# Volume and Volume claims
#
# Mysql
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    name: db-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: data-db
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: db-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-data
  labels:
    name: solr-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: solr-db
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-claim
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: solr-data
