apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geodb
    spec:
      containers:
        - name: geodb
          image: eu.gcr.io/powop-1349/geodb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-password
