apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geoserver
    spec:
      containers:
        - name: activemq
          image: eu.gcr.io/powop-1349/geoserver:latest
          ports:
            - containerPort: 8009
