apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: portal
    spec:
      containers:
        - name: portal
          image: eu.gcr.io/powop-1349/portal:latest
          ports:
            - containerPort: 8009
