# Portal database
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
        - name: db
          image: eu.gcr.io/powop-1349/db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: db
  ports:
    - port: 3306

---
# Geoserver database
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geodb
    spec:
      containers:
        - name: geodb
          image: eu.gcr.io/powop-1349/geodb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-db-secrets
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: geodb
spec:
  selector:
    name: geodb
  ports:
    - port: 3306

---
# Tomcat configurations: Portal, Harvester, Geoserver

# Portal
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: portal
    spec:
      containers:
        - name: portal
          image: eu.gcr.io/powop-1349/portal:latest
          ports:
            - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: portal
spec:
  selector:
    name: portal
  ports:
    - port: 8009

---
# Harvester
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harvester
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: harvester
    spec:
      containers:
        - name: harvester
          image: eu.gcr.io/powop-1349/harvester:latest
          ports:
            - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: harvester
spec:
  selector:
    name: harvester
  ports:
    - port: 8009
     
# Geoserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geoserver
    spec:
      containers:
        - name: activemq
          image: eu.gcr.io/powop-1349/geoserver:latest
          ports:
            - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: geoserver
spec:
  selector:
    name: geoserver
  ports:
    - port: 8009

# Apache
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: apache
    spec:
      containers:
        - name: apache
          image: eu.gcr.io/powop-1349/apache:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  selector:
    name: apache
  ports:
    - port: 80
  type: LoadBalancer


# Solr
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: solr
    spec:
      containers:
        - name: solr
          image: eu.gcr.io/powop-1349/solr:latest
          ports:
            - containerPort: 8983
---
apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    name: solr
  ports:
    - port: 8983

# ActiveMQ
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: activemq
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:5.12.0
          ports:
            - containerPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    name: activemq
  ports:
    - port: 61616
