apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: solr
    spec:
      containers:
        - name: solr
          image: eu.gcr.io/powop-1349/solr:latest
          ports:
            - containerPort: 8983
