cluster: powo-prod
deleteExisting: true
dns:
  - zone: plantsoftheworldonline-org
    name: plantsoftheworldonline.org.
    service: ingress
  - zone: colplanta
    name: colplanta.org.
    service: ingress-colplanta
  - zone: usefulplantsofboyaca
    name: usefulplantsofboyaca.org.
    service: ingress-upb
  - zone: colfungi
    name: colfungi.org.
    service: ingress-colfungi
environment: prod
schedule: "0 12 * * SUN"
strictErrorChecking: true
dataConfig: https://raw.githubusercontent.com/RBGKew/powo-data/master/data-prod.json