cluster: powo-prod
deleteExisting: true
dns:
  - zone: prod-plantsoftheworld-online
    name: prod.plantsoftheworld.online.
    service: ingress
  - zone: prod-plantsoftheworld-online
    name: colplanta.prod.plantsoftheworld.online.
    service: ingress-colplanta
  - zone: prod-plantsoftheworld-online
    name: colfungi.prod.plantsoftheworld.online.
    service: ingress-colfungi
  - zone: usefulplantsofboyaca
    name: usefulplantsofboyaca.org.
    service: ingress-upb
environment: prod
schedule: "0 12 * * SUN"
strictErrorChecking: true
dataConfig: https://raw.githubusercontent.com/RBGKew/powo-data/master/data-prod.json