cluster: powo-prod
deleteExisting: true
dns:
  - zone: plantsoftheworldonline-org
    name: plantsoftheworldonline.org.
    service: ingress
environment: prod
schedule: "0 12 * * SUN"
strictErrorChecking: true
