apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: activemq
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:5.12.0
          ports:
            - containerPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    name: activemq
  ports:
    - port: 61616
