apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: {{ .Values.portal.replicas }}
  template:
    metadata:
      labels:
        name: portal
        env: {{ .Release.Name }}
    spec:
      containers:
        - name: portal
          image: eu.gcr.io/powop-1349/portal:{{ .Values.portal.version }}
          ports:
            - containerPort: 8009
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
          env:
{{- if .Values.db.password }}
            - name: JDBC_DRIVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: jdbc-driver-password
{{- end }}
{{- if .Values.google_analytics_code }}
            - name: GOOGLE_ANALYTICS_CODE
              valueFrom:
                secretKeyRef:
                  name: service-keys
                  key: google-analytics-code
{{- end }}
{{- if .Values.db.cloudsql.enabled }}
            - name: JDBC_DRIVER_URL
              value: jdbc:mysql://127.0.0.1:3306/emonocot
{{- template "cloudsql_proxy" . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: portal
spec:
  selector:
    name: portal
  ports:
    - port: 8009
