---
db:
  version: 2.0.0-3132201
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-3132201
portal:
  version: 2.0.0-3132201
  replicas: 1
  google_analytics_code: GTM-5KXDJXF
harvester:
  version: 2.0.0-3132201
apache:
  version: 2.0.0-3132201
solr:
  version: 2.0.0-3132201
  storage:
    type: ssd
    size: 20
