---
db:
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-7a516bd
portal:
  version: 2.0.0-7a516bd
  replicas: 2
harvester:
  version: 2.0.0-7a516bd
apache:
  version: 2.0.0-7a516bd
solr:
  version: 2.0.0-7a516bd
  storage:
    type: ssd
    size: 20
