---
db:
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-e9d72a1
portal:
  version: 2.0.0-e9d72a1
  replicas: 2
harvester:
  version: 2.0.0-e9d72a1
apache:
  version: 2.0.0-e9d72a1
solr:
  version: 2.0.0-e9d72a1
  storage:
    type: ssd
    size: 20
