---
db:
  version: 2.0.0-4fc20a8
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-4fc20a8
portal:
  version: 2.0.0-0bb63ac
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
  environment_type: prod
colplanta:
  enabled: true
upb:
  enabled: true
colfungi:
  enabled: true
harvester:
  version: 2.0.0-4fc20a8
solr:
  version: 2.0.0-4fc20a8
  storage:
    type: ssd
    size: 20
