---
db:
  version: 2.0.0-136423b
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-136423b
portal:
  version: 2.0.0-a59be51
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
colplanta:
  enabled: true
upb:
  enabled: true
colfungi:
  enabled: true
harvester:
  version: 2.0.0-136423b
solr:
  version: 2.0.0-136423b
  storage:
    type: ssd
    size: 20
