---
db:
  version: 2.0.0-e4f4144
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-e4f4144
portal:
  version: 2.0.0-e4f4144
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
  environment_type: prod
colplanta:
  enabled: true
upb:
  enabled: true
colfungi:
  enabled: true
harvester:
  version: 2.0.0-e4f4144
solr:
  version: 2.0.0-e4f4144
  storage:
    type: ssd
    size: 20
