---
db:
  version: 2.0.0-3e1255f
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-3e1255f
portal:
  version: 2.0.0-27caed7
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
  environment_type: prod
  resources:
    limits:
      cpu: "500m"
      memory: "750Mi"
    requests:
      cpu: "50m"
      memory: "600Mi"
colplanta:
  enabled: true
  google_analytics_code: GTM-KZNXKZM
colfungi:
  enabled: true
  google_analytics_code: GTM-K94N6PR
harvester:
  version: 2.0.0-5ec5007
solr:
  version: 2.0.0-5ec5007
  storage:
    type: ssd
    size: 20
