---
db:
  version: 2.0.0-5a48b19
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-5a48b19
portal:
  version: 2.0.0-5a48b19
  replicas: 1
  google_analytics_code: GTM-5KXDJXF
harvester:
  version: 2.0.0-5a48b19
apache:
  version: 2.0.0-5a48b19
solr:
  version: 2.0.0-5a48b19
  storage:
    type: ssd
    size: 20
