---
db:
  version: 2.0.0-eb990ab
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-eb990ab
portal:
  version: 2.0.0-eb990ab
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
harvester:
  version: 2.0.0-eb990ab
apache:
  version: 2.0.0-eb990ab
solr:
  version: 2.0.0-eb990ab
  storage:
    type: ssd
    size: 20
