---
db:
  version: 2.0.0-eb990ab
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
solr:
  version: 2.0.0-eb990ab
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-eb990ab
harvester:
  version: 2.0.0-9484d01
portal:
  version: 2.0.0-fc7e808
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
colplanta:
  enabled: true
upb:
  enabled: true
