---
db:
  version: 2.0.0-297b3c7
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-297b3c7
portal:
  version: 2.0.0-297b3c7
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
colplanta:
  enabled: true
upb:
  enabled: true
colfungi:
  enabled: true
harvester:
  version: 2.0.0-297b3c7
solr:
  version: 2.0.0-297b3c7
  storage:
    type: ssd
    size: 20
