---
db:
  version: 2.0.0-e4f4144
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-e4f4144
portal:
  version: 2.0.0-6fc1d28
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
  environment_type: prod
colplanta:
  enabled: true
  google_analytics_code: GTM-KZNXKZM
colfungi:
  enabled: true
  google_analytics_code: GTM-K94N6PR
upb:
  enabled: true
harvester:
  version: 2.0.0-e4f4144
solr:
  version: 2.0.0-e4f4144
  storage:
    type: ssd
    size: 20
