---
db:
  version: 2.0.0-84f6423
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-84f6423
portal:
  version: 2.0.0-84f6423
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
colplanta:
  enabled: true
upb:
  enabled: true
colfungi:
  enabled: true
harvester:
  version: 2.0.0-e6129cf
solr:
  version: 2.0.0-84f6423
  storage:
    type: ssd
    size: 20
