---
db:
  version: 2.0.0-12ccc24
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-12ccc24
portal:
  version: 2.0.0-12ccc24
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
  environment_type: prod
colplanta:
  enabled: true
  google_analytics_code: GTM-KZNXKZM
colfungi:
  enabled: true
  google_analytics_code: GTM-K94N6PR
upb:
  enabled: true
harvester:
  version: 2.0.0-12ccc24
solr:
  version: 2.0.0-12ccc24
  storage:
    type: ssd
    size: 20
