---
db:
  version: 2.0.0-eb990ab
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-eb990ab
portal:
  version: 2.0.0-c14e9f1
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
colplanta:
  enabled: true
upb:
  enabled: true
harvester:
  version: 2.0.0-c14e9f1
solr:
  version: 2.0.0-eb990ab
  storage:
    type: ssd
    size: 20
