---
db:
  version: 2.0.0-8e7f00f
  database: powo
  user: powo
  storage:
    type: ssd
    size: 20
geoserver:
  version: 2.0.0-8e7f00f
portal:
  version: 2.0.0-ee960e4
  replicas: 2
  google_analytics_code: GTM-5KXDJXF
  environment_type: prod
colplanta:
  enabled: true
  google_analytics_code: GTM-KZNXKZM
colfungi:
  enabled: true
  google_analytics_code: GTM-K94N6PR
upb:
  enabled: true
harvester:
  version: 2.0.0-8e7f00f
solr:
  version: 2.0.0-8e7f00f
  storage:
    type: ssd
    size: 20
