---
db:
  version: 2.0.0-eb22edd
  database: powo
  user: powo
  storage:
    type: standard
    size: 10
    onrelease: Delete
geoserver:
  version: 2.0.0-eb22edd
  replicas: 1
  database: gis
  user: geoserver
portal:
  version: 2.0.0-eb22edd
  replicas: 1
harvester:
  version: 2.0.0-eb22edd
  replicas: 1
apache:
  version: 2.0.0-eb22edd
  replicas: 1
solr:
  version: 2.0.0-eb22edd
  storage:
    type: standard
    size: 10
    onrelease: Delete
colplanta:
  enabled: false
  apache:
    replicas: 1
  portal:
    replicas: 1
upb:
  enabled: false
  apache:
    replicas: 1
  portal:
    replicas: 1
