---
db:
  database: powo
  user: powo
  storage:
    type: standard
    size: 10
    onrelease: Delete
  resources:
    limits:
      cpu: "1"
      memory: "2.5Gi"
    requests:
      cpu: "100m"
      memory: "500Mi"
geoserver:
  replicas: 1
  database: gis
  user: geoserver
  resources:
    limits:
      cpu: "800m"
      memory: "2Gi"
    requests:
      cpu: "100m"
      memory: "1Gi"
portal:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "50m"
      memory: "400Mi"
harvester:
  replicas: 1
  resources:
    limits:
      cpu: "1.5"
      memory: "2.5Gi"
    requests:
      cpu: "50m"
      memory: "1.5Gi"
ingress:
  replicas: 1
  resources:
    limits:
      cpu: "100m"
      memory: "50Mi"
    requests:
      cpu: "50m"
      memory: "10Mi"
solr:
  storage:
    type: standard
    size: 10
    onrelease: Delete
  resources:
    limits:
      cpu: "1.5"
      memory: "1.5Gi"
    requests:
      cpu: "50m"
      memory: "500Mi"
colplanta:
  enabled: false
  ingress:
    replicas: 1
  portal:
    replicas: 1
colfungi:
  enabled: false
  ingress:
    replicas: 1
  portal:
    replicas: 1
upb:
  enabled: false
  ingress:
    replicas: 1
  portal:
    replicas: 1
