---
db:
  # When using gsql, enabled should be true. Otherwise, a mysql instance will be
  # spun up in a container
  cloudsql:
    enabled: false
  version: 2.0.0-7a516bd
  database: powo
  user: powo
  storage:
    type: standard
    size: 10
    onrelease: Delete
geoserver:
  version: 2.0.0-7a516bd
  replicas: 1
  database: gis
  user: geoserver7a516bd
portal:
  version: 2.0.0-7a516bd
  replicas: 1
harvester:
  version: 2.0.0-7a516bd
  replicas: 1
apache:
  version: 2.0.0-7a516bd
  replicas: 1
solr:
  version: 2.0.0-7a516bd
  storage:
    type: standard
    size: 10
    onrelease: Delete
colplanta:
  enabled: false
  apache:
    replicas: 1
  portal:
    replicas: 1
upb:
  enabled: false
  apache:
    replicas: 1
  portal:
    replicas: 1
