---
db:
  version: 2.0.0-eb22edd
  database: powo
  user: powo
  storage:
    type: standard
    size: 10
    onrelease: Delete
  resources:
    limits:
      cpu: "1"
      memory: "2.5Gi"
    requests:
      cpu: "100m"
      memory: "500Mi"
geoserver:
  version: 2.0.0-eb22edd
  replicas: 1
  database: gis
  user: geoserver
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "700Mi"
portal:
  version: 2.0.0-e9d72a1
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "400Mi"
    requests:
      cpu: "100m"
      memory: "300Mi"
harvester:
  version: 2.0.0-1d9f006
  replicas: 1
  resources:
    limits:
      cpu: "1.5"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "700Mi"
apache:
  version: 2.0.0-e9d72a1
  replicas: 1
  resources:
    limits:
      cpu: "100m"
      memory: "50Mi"
    requests:
      cpu: "50m"
      memory: "10Mi"
solr:
  version: 2.0.0-eb22edd
  storage:
    type: standard
    size: 10
    onrelease: Delete
  resources:
    limits:
      cpu: "100m"
      memory: "800Mi"
    requests:
      cpu: "50m"
      memory: "500Mi"
colplanta:
  enabled: false
  apache:
    replicas: 1
  portal:
    replicas: 1
upb:
  enabled: false
  apache:
    replicas: 1
  portal:
    replicas: 1
